# "test" suffix properties file. Scopes name samples: "test", "web-test", "api-test", etc.
# Overrides application.yml default properties
spring:
  datasource:
    host: DB_MYSQL_DESAENV04_DESAFIO_DESAFIO_ENDPOINT
    db: desafio
    username: desafio_WPROD
    password: DB_MYSQL_DESAENV04_DESAFIO_DESAFIO_WPROD
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect